# Name of your site (displayed in the header)
name: CM Engineers
title: CMEngineers.com.au

# Short bio or description (displayed in the header)
description: CM Engineers. Tailored IT services for you

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - README.md